services:
  - type: static
    name: invitaciones
    env: static
   buildCommand: npm install && npm run build
   publishPath: dist
    redirects:
      - source: /*
        destination: /index.html
        status: 200
